# Site settings
# in the templates available like {{ site.myvariable }}.
title: Software Engineer
email: your-email@domain.com
brand: Ryann McQuilton
headline: Software Engineer &middot; Los Angeles, CA
description: > # this means to ignore newlines until "baseurl:"
  Full-stack software engineering with Ruby, Rails, JavaScript,
  React, SQL, HTML, CSS and other back-end and front-end technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryannmcq.github.io/" # the base hostname & protocol for your site
copyright: 2018 Ryann McQuilton

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1
