# Site settings
# in the templates available like {{ site.myvariable }}.
title: Software Engineer
email: rmcquilton@gmail.com
brand: Ryann McQuilton
headline: Software Engineer &middot; Los Angeles, CA
description: > # this means to ignore newlines until "baseurl:"
  Full-stack web development with Ruby, Rails, JavaScript, Node,
  React, SQL, HTML, CSS and other backend and frontend technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryannmcq.github.io/" # the base hostname & protocol for your site
copyright: 2018 Ryann McQuilton

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: rmcquilton@gmail.com

# Tracking
googleAnalitycsID: UA-83933844-1
